"""
LeetCode #389 - Find the Difference
Difficulty: Easy
Topics: String, Hash Table, Bit Manipulation
Date: 2026-09-23
Time spent: [X] min
Status: [Solved / Looked at solution / Timeout]

## Problem Statement
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more
letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

## Idea
Use Counter to count character frequencies in both strings. Compare the counts
and return the character whose count differs. Using .get(char, 0) avoids KeyError
when the character doesn't exist in s.

## Complexity
- Time: O(n) where n = len(t)
- Space: O(n) for the two Counter objects

## Submission Log
- [ ] Submitted on LeetCode
- [ ] Passed all test cases
"""


from collections import Counter


class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        count_t = Counter(t)
        count_s = Counter(s)

        for char in count_t:
            if count_t[char] != count_s.get(char, 0):
                return char
